apiVersion: v1
kind: Pod
metadata:
  name: test-pd1
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox
    name: busybox
    command: ["/bin/sh","-c"]
    args: ["sleep 1000"]
    volumeMounts:
    - mountPath: /data
      name: cache-volume
  
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
