apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-09-25T10:54:11Z"
    labels:
      app: mealie
    name: mealie
    namespace: mealie
    resourceVersion: "35081"
    uid: c3287e1e-cbc2-4e89-ad25-8e1703ab714d
  spec:
    clusterIP: 10.43.39.94
    clusterIPs:
    - 10.43.39.94
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: mealie
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
